home tasks
tarakhu/SauceDemo_QA22_TarletskiyVadim pull request #1
Opened 2022-12-26 20:15 UTC by tarakhu

2022-12-26 21:24 UTC, voropa requested changes

2022-12-26 21:24 UTC, voropa commented on .gitignore
> +target/
Вся папка .idea должна быть в .gitignore

2022-12-26 21:24 UTC, voropa commented on src/test/java/Tests/CheckOutTest.java
> +    @DataProvider
Какой смысл добавлять dataProvider, если в нем только одна строка с данными и соответсвенно тест будет выполняться только  один раз?

2022-12-26 21:24 UTC, voropa commented on src/test/java/Tests/LoginTest.java
> +@Listeners(TestListener.class)
@Listener дотсаточно указать в BaseTest классе, а все унаследованные от него классы будут его использовать

2022-12-26 21:24 UTC, voropa commented on src/test/java/Tests/LoginTest.java
> +    @Test(groups = "smoke", description = "позитивный тест на логин")
группы должны быть указаны в {},  иначе не будет работь
groups = {"smoke"}

2022-12-26 21:24 UTC, voropa commented on src/test/java/Tests/PositiveCheckoutStepOneTest.java
> +    @DataProvider
То же самое, зачем вам тут dataProvider?

2022-12-26 21:24 UTC, voropa commented on src/test/java/Tests/PositiveCheckoutStepOneTest.java
> +public class PositiveCheckoutStepOneTest extends BaseTest{
И зачем вы делите negative и positve тесты на разные классы? Обьедините их в один класс

2022-12-26 21:24 UTC, voropa commented on src/test/java/Tests/SortByNameZ_ATest.java
> +    public void productsTest(String testItemName, String expectedItemPrice, String expectedItemDescription)  {
А чем этот тест отличается от теста в ProductTests классе?

2023-01-01 18:29 UTC, tarakhu commented on src/test/java/Tests/CheckOutTest.java
> +    @DataProvider
убрал

2023-01-01 18:32 UTC, tarakhu commented on src/test/java/Tests/LoginTest.java
> +@Listeners(TestListener.class)
оставил только в BaseTest

2023-01-01 18:33 UTC, tarakhu commented on src/test/java/Tests/LoginTest.java
> +    @Test(groups = "smoke", description = "позитивный тест на логин")
исправил

2023-01-01 18:34 UTC, tarakhu commented on src/test/java/Tests/PositiveCheckoutStepOneTest.java
> +    @DataProvider
убрал

2023-01-01 18:40 UTC, tarakhu commented on src/test/java/Tests/PositiveCheckoutStepOneTest.java
> +public class PositiveCheckoutStepOneTest extends BaseTest{
исправил

2023-01-01 18:40 UTC, tarakhu commented on src/test/java/Tests/SortByNameZ_ATest.java
> +    public void productsTest(String testItemName, String expectedItemPrice, String expectedItemDescription)  {
тест был недоделан, сейчас все ок.

2023-01-01 18:40 UTC, tarakhu commented on src/test/java/Tests/SortByNameZ_ATest.java
> +    public void productsTest(String testItemName, String expectedItemPrice, String expectedItemDescription)  {
тест был недоделан, сейчас все ок.

2023-01-01 18:40 UTC, tarakhu commented on .gitignore
> +target/
не понимаю что я должен сделать..

2023-01-26 17:43 UTC, merged