Dz
tarakhu/SauceDemo_QA22_TarletskiyVadim pull request #2
Opened 2023-01-02 16:35 UTC by tarakhu

2023-01-04 16:11 UTC, voropa requested changes

2023-01-04 16:11 UTC, voropa commented on .gitignore
> +target/
Добавьте сюда еще .idea/
чтобы все файлы, которые внутри папки .idea не попадали в комиты

2023-01-04 16:11 UTC, voropa commented on src/test/resources/allure.properties
> +allure.link.issue.pattern=https://instagram.com/{}
Точно нужны ссылки на инстаграм тут?)

2023-01-04 16:11 UTC, voropa commented on src/test/java/Tests/TotalPriceTest.java
> +    String itemName1 = "Sauce Labs Backpack";
По java code convention не  рекомендуется использовать численные индексы вназвании переменных и т.д, лучше в таком случае их текстом писать хотя бы: firstItem, secondItem

2023-01-18 19:34 UTC, voropa requested changes

2023-01-18 19:34 UTC, voropa commented on src/test/java/Pages/CartPage.java
> +        PageFactory.initElements(driver,this);
Можно не дуюлировать этот код в каждом page-классе, так как он уже есть в конструкторе BasePage

2023-01-18 19:34 UTC, voropa commented on src/test/java/Pages/ItemLargeSizePage.java
> +    @FindBy(xpath = "//div[@class='inventory_details_name large_size']")
Вроде у вас одинаковый локатор для всех 3х элементов. Вы запускаали тесты, поосле этиих изменений, они работают вообще?

2023-01-18 19:34 UTC, voropa commented on src/test/java/Pages/CartPage.java
> +    @FindBy(xpath = "//button[@id ='checkout']")
А почему этот элемент через FindBy обьявили, а остальные оставили без изменений? У вас весь page класс должен быть в едином стиле: либо page object либо pagefactory.

2023-01-18 19:34 UTC, voropa commented on src/test/java/Pages/LoginPage.java
>      private final static By USERNAME_INPUT_LOCATOR = By.cssSelector("#user-name");
То же самое тут, почему USERANME_INPUT остался без FindBy?

2023-01-19 16:31 UTC, tarakhu commented on src/test/java/Pages/ItemLargeSizePage.java
> +    @FindBy(xpath = "//div[@class='inventory_details_name large_size']")
да я вчера перед пушем проверял тесты и все было ок, но оказывается у меня на этом тесте не стояла группа для него вот и упустил ошибку)

2023-01-19 16:31 UTC, tarakhu commented on src/test/java/Pages/LoginPage.java
>      private final static By USERNAME_INPUT_LOCATOR = By.cssSelector("#user-name");
потому что он используется в буленовском методе у меня в тесте на проверку логаута, я так понимаю я не могу использовать файнд бай тогда

2023-01-19 16:35 UTC, tarakhu commented on src/test/java/Pages/CartPage.java
> +    @FindBy(xpath = "//button[@id ='checkout']")
это единственный элемент который не используется в динамических локаторах или буленовских методах либо не ищет элемент внутри другого

2023-01-19 16:35 UTC, tarakhu commented on src/test/java/Pages/ItemLargeSizePage.java
> +    @FindBy(xpath = "//div[@class='inventory_details_name large_size']")
ошибся, исправил

2023-01-19 16:37 UTC, tarakhu commented on src/test/java/Pages/CartPage.java
> +        PageFactory.initElements(driver,this);
понял, исправил

2023-01-19 16:38 UTC, tarakhu commented on src/test/resources/allure.properties
> +allure.link.issue.pattern=https://instagram.com/{}
убрал

2023-01-22 12:01 UTC, voropa approved these changes

2023-01-22 12:01 UTC, voropa commented on src/test/java/Pages/CartPage.java
> +    @FindBy(xpath = "//button[@id ='checkout']")
Вот, значит верните все, как было, чтобы был везде page object в этом классе, без FindBy

2023-01-22 12:01 UTC, voropa commented on src/test/java/Pages/LoginPage.java
>      private final static By USERNAME_INPUT_LOCATOR = By.cssSelector("#user-name");
Почему, можете, делаете boolean метод: return usernameInput.isDisplayed()

2023-01-26 17:43 UTC, merged